name: Say Hello World

on:
  push:
    branches:
      - main

jobs:
  hello_world:
    runs-on: ubuntu-18.04
    steps:
      - name: Echo de tu message
        run: echo "Hola Nando"
      - name: Dime la fecha
        run: date
      - run: ls -l